kind: pipeline
type: docker
name: devgardenci

trigger:
    event:
      - push

steps:
  - name: install-dependencies
    image: node:21
    commands:
      - node -v
      - yarn -v
  - name: build
    image: node:21
    commands:
      - pwd
      - ls
      - cd Sources
      - yarn install
      - yarn build